# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('fill', models.CharField(max_length=7)),
                ('stroke', models.CharField(max_length=7)),
                ('stroke_width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canvas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cx', models.IntegerField()),
                ('cy', models.IntegerField()),
                ('r', models.IntegerField()),
                ('fill', models.CharField(max_length=7)),
                ('stroke', models.CharField(max_length=7)),
                ('strike_width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('fill', models.CharField(max_length=7)),
                ('stroke', models.CharField(max_length=7)),
                ('strike_width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=7)),
                ('fill', models.CharField(max_length=7)),
                ('stroke', models.CharField(max_length=7)),
                ('strike_width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polygon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('fill', models.CharField(max_length=7)),
                ('stroke', models.CharField(max_length=7)),
                ('strike_width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rectangle',
                'managed': True,
            },
        ),
    ]
